package org.aa4h.samples;

// Generated Dec 13, 2007 2:21:23 PM by Hibernate Tools 3.2.0.CR1

/**
 * Bonus generated by hbm2java
 */
public class Bonus implements java.io.Serializable {

	private int empno;
	private float sal;
	private float comm;

	public Bonus() {
	}

	public Bonus(int empno, float sal, float comm) {
		this.empno = empno;
		this.sal = sal;
		this.comm = comm;
	}

	public int getEmpno() {
		return this.empno;
	}

	public void setEmpno(int empno) {
		this.empno = empno;
	}


	public float getSal() {
		return this.sal;
	}

	public void setSal(float sal) {
		this.sal = sal;
	}

	public float getComm() {
		return this.comm;
	}

	public void setComm(float comm) {
		this.comm = comm;
	}

	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String TAB = "    ";
	
	    StringBuilder retValue = new StringBuilder();
	    
	    retValue.append("Bonus ( ")
	        .append(super.toString()).append(TAB)
	        .append("empno = ").append(this.empno).append(TAB)
	        .append("sal = ").append(this.sal).append(TAB)
	        .append("comm = ").append(this.comm).append(TAB)
	        .append(" )");
	    
	    return retValue.toString();
	}

}
