package org.aa4h.samples;

// Generated Dec 13, 2007 2:21:23 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private int empno;
	private Emp mgr;
	private Job job;
	private Dept dept;
	private String ename;
	private Date hiredate;
	private float sal;
	private float comm;
	private Set<Emp> emps = new HashSet<Emp>(0);
	private Set<Bonus> bonuses = new HashSet<Bonus>(0);

	public Emp() {
	}

	public Emp(int empno, Job job, Dept dept, String ename, Date hiredate,
			float sal, float comm) {
		this.empno = empno;
		this.job = job;
		this.dept = dept;
		this.ename = ename;
		this.hiredate = hiredate;
		this.sal = sal;
		this.comm = comm;
	}

	public Emp(int empno, Emp mgr, Job job, Dept dept, String ename,
			Date hiredate, float sal, float comm, Set<Emp> emps,
			Set<Bonus> bonuses) {
		this.empno = empno;
		this.mgr = mgr;
		this.job = job;
		this.dept = dept;
		this.ename = ename;
		this.hiredate = hiredate;
		this.sal = sal;
		this.comm = comm;
		this.emps = emps;
		this.bonuses = bonuses;
	}

	public int getEmpno() {
		return this.empno;
	}

	public void setEmpno(int empno) {
		this.empno = empno;
	}

	public Emp getMgr() {
		return this.mgr;
	}

	public void setMgr(Emp mgr) {
		this.mgr = mgr;
	}

	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Date getHiredate() {
		return this.hiredate;
	}

	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	public float getSal() {
		return this.sal;
	}

	public void setSal(float sal) {
		this.sal = sal;
	}

	public float getComm() {
		return this.comm;
	}

	public void setComm(float comm) {
		this.comm = comm;
	}

	public Set<Emp> getEmps() {
		return this.emps;
	}

	public void setEmps(Set<Emp> emps) {
		this.emps = emps;
	}

	public Set<Bonus> getBonuses() {
		return this.bonuses;
	}

	public void setBonuses(Set<Bonus> bonuses) {
		this.bonuses = bonuses;
	}

	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String TAB = "    ";
	
	    StringBuilder retValue = new StringBuilder();
	    
	    retValue.append("Emp ( ")
	        .append(super.toString()).append(TAB)
	        .append("empno = ").append(this.empno).append(TAB)
	        //.append("mgr = ").append(this.mgr).append(TAB)
	        .append("job = ").append(this.job).append(TAB)
	        .append("dept = ").append(this.dept).append(TAB)
	        .append("ename = ").append(this.ename).append(TAB)
	        .append("hiredate = ").append(this.hiredate).append(TAB)
	        .append("sal = ").append(this.sal).append(TAB)
	        .append("comm = ").append(this.comm).append(TAB)
	        //.append("emps = ").append(this.emps).append(TAB)
	        .append("bonuses = ").append(this.bonuses).append(TAB)
	        .append(" )");
	    
	    return retValue.toString();
	}

}
