package test.com.heliosapm.aa4h.pojos;

// Generated Dec 13, 2007 2:21:23 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job implements java.io.Serializable {

	private long jobId;
	private String jobName;
	private Set<Emp> emps = new HashSet<Emp>(0);

	public Job() {
	}

	public Job(long jobId, String jobName) {
		this.jobId = jobId;
		this.jobName = jobName;
	}

	public Job(long jobId, String jobName, Set<Emp> emps) {
		this.jobId = jobId;
		this.jobName = jobName;
		this.emps = emps;
	}

	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public Set<Emp> getEmps() {
		return this.emps;
	}

	public void setEmps(Set<Emp> emps) {
		this.emps = emps;
	}

	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String TAB = "    ";
	
	    StringBuilder retValue = new StringBuilder();
	    
	    retValue.append("Job ( ")
	        .append(super.toString()).append(TAB)
	        .append("jobId = ").append(this.jobId).append(TAB)
	        .append("jobName = ").append(this.jobName).append(TAB)
	        //.append("emps = ").append(this.emps).append(TAB)
	        .append(" )");
	    
	    return retValue.toString();
	}

}
