package test.com.heliosapm.aa4h.pojos;

// Generated Dec 13, 2007 2:21:23 PM by Hibernate Tools 3.2.0.CR1

/**
 * Salgrade generated by hbm2java
 */
public class Salgrade implements java.io.Serializable {

	private long grade;
	private float losal;
	private float hisal;

	public Salgrade() {
	}

	public Salgrade(long grade, float losal, float hisal) {
		this.grade = grade;
		this.losal = losal;
		this.hisal = hisal;
	}

	public long getGrade() {
		return this.grade;
	}

	public void setGrade(long grade) {
		this.grade = grade;
	}

	public float getLosal() {
		return this.losal;
	}

	public void setLosal(float losal) {
		this.losal = losal;
	}

	public float getHisal() {
		return this.hisal;
	}

	public void setHisal(float hisal) {
		this.hisal = hisal;
	}

	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String TAB = "    ";
	
	    StringBuilder retValue = new StringBuilder();
	    
	    retValue.append("Salgrade ( ")
	        .append(super.toString()).append(TAB)
	        .append("grade = ").append(this.grade).append(TAB)
	        .append("losal = ").append(this.losal).append(TAB)
	        .append("hisal = ").append(this.hisal).append(TAB)
	        .append(" )");
	    
	    return retValue.toString();
	}

}
